Support serialization of url query parameters
os-js/osjs-client pull request #182
Opened 2022-07-26 13:43 UTC by mahsashadi

2022-07-26 14:17 UTC, andersevenrud requested changes

2022-07-26 14:17 UTC, andersevenrud commented on src/utils/fetch.js
> +  const pairs = Object.entries(data).map(([key, val]) => {
Might be better to just filter out any null-ish values before doing the encoding. The backend doesn't really take `null` or `undefined` values anyway.

This way you can just do the following:

```js
const pairs = Object.entries(data)
  .filter(([, val]) => val !== null && val !== undefined)
  .map(([key, val]) => {
    const value = typeof val === 'object' ? JSON.stringify(val) : val;
    return `${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
  });
```

2022-07-27 06:15 UTC, mahsashadi commented on src/utils/fetch.js
> +//  */
Oops! sorry for that.

2022-07-27 06:24 UTC, mahsashadi commented
@andersevenrud changes are done.

2022-07-27 17:34 UTC, andersevenrud commented
> filtering client options passed

I'm not I sure I fully understand the issue.

2022-07-27 19:02 UTC, andersevenrud approved these changes

2022-07-27 19:03 UTC, merged